config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "dashboard#index"
  get "/dashboard", to: "dashboard#index", as: 'user_root'
  get "/catalog", to:"catalog#index"
  get "/catalog/:id", to: "catalog#show", as: 'show_service'
  resources :services do
    resources :orders do
      resources :reviews, only: [:new, :create]
      member do
        post "accept"
        post "cancel"
        post "complete"
        post "reject"
      end
    end
  end
  resources :profiles, only: [:show] do
	  collection do
		  get 'wizard'
		  patch "submit_wizard"
	  end
  end
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :service
  belongs_to :user

  delegate :headline, to: :service
  delegate :description, to: :service
  delegate :price, to: :service

  scope :unaccepted_rejected, -> { where(accepted_at: nil).where("rejected_at IS NOT NULL") }
  scope :unaccepted_awaiting_response, -> { where(accepted_at: nil,rejected_at: nil) }
  scope :unaccepted, -> { where(accepted_at: nil) }
  scope :accepted, -> { where("accepted_at IS NOT NULL") }

  after_initialize :set_default_values
  after_create do
    UserMailer.order_made(self).deliver_now
  end

  def complete?
    completed_at.present?
  end

  protected
  def set_default_values
    self.appointment_time ||= 2.hours.from_now.at_beginning_of_hour
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :order
  belongs_to :user
  belongs_to :from_user, class_name: "User"
end

app/models/service.rb
class Service < ApplicationRecord
  validates :headline, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0}

  belongs_to :user
  belongs_to :category
  has_many :orders
  acts_as_mappable through: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :services
  has_many :orders, through: :services
  has_many :orders_i_placed, class_name: 'Order'
  has_many :reviews

  acts_as_mappable

  has_attached_file :avatar, styles: { tiny: "75x75#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def accepted_orders_i_have_or_placed
    (orders.accepted.all + orders_i_placed.accepted.all)
  end

  def services_in_my_area(range,unit=:miles)
    Service.joins(:user).within(range, :units => unit, :origin => [self.lat, self.lng])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :set_headers

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:lat, :lng, :name, :phone, :about_me, :avatar, :location_description])
  end

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Expose-Headers'] = 'ETag'
    headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
    headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'
    headers['Access-Control-Max-Age'] = '86400'
  end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
	def index
		params[:within] ||= 10
		params[:unit] ||= "miles"

    if current_user
      @services = current_user.services_in_my_area(params[:within].to_i)
    else
      @services = Service.all
    end
	end

	def show
		@service = Service.find(params[:id])
	end
end

app/controllers/catelog_controller.rb
class CatelogController < ApplicationController
	def index

	end

	def show
		@service = Service.find(params[:id])
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @recent_postings = Service.order(created_at: :desc).limit(5)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  def new
    @service = Service.find(params[:service_id])
    @order = current_user.orders.build(service_id: params[:service_id])
  end

  def create
    @order = Order.new(params[:order].permit(:appointment_time))
    @order.service_id = params[:service_id]
    @order.user_id = current_user.id
    @order.save!
    flash[:notify] = "Your order was created"
    redirect_to "/dashboard"
  end

  def accept
    @order = Order.find(params[:id])
    @order.accepted_at = Time.now
    @order.save
    redirect_to "/dashboard"
  end

  def complete
    @order = Order.find(params[:id])
    @order.completed_at = Time.now
    @order.save
    redirect_to new_service_order_review_path(@order.service, @order)
  end

  def cancel
    # Technically, we should not lose the accepted information here, maybe this can be solved by audit-logs
    @order = Order.find(params[:id])
    @order.accepted_at = nil
    @order.cancelled_at = Time.now
    @order.save
    redirect_to "/dashboard"
  end

  def reject
    @order = Order.find(params[:id])
    @order.rejected_at = Time.now
    @order.save
    redirect_to "/dashboard"
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def wizard
	  @user = current_user
  end
  def submit_wizard
	  current_user.update_attributes(params[:user].permit(:phone,:name, :lat, :lng, :avatar))
	  redirect_to "/dashboard"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/profiles/wizard' # Or :prefix_to_your_route
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :setup_associations
  def new

  end

  def create
    @review.attributes = params[:review].permit(:rating, :description)
    @review.save

    redirect_to profile_path(@review.user)
  end

  protected
  def setup_associations
    @order = Order.find(params[:order_id])
    @service = Service.find(params[:service_id])
    @review = Review.new
    @review.order = @order
    if @service.user == current_user
      @review.user = @order.user
    else
      @review.user = @service.user
    end
    @review.from_user_id = current_user.id
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!

  def index
          redirect_to "/catalog"
  end

  def new
    @service = current_user.services.build
  end

  def create
    @service = current_user.services.build(params[:service].permit([:headline, :description, :fixed_rate, :price, :category_id, :seeking_help, :expiration_date]))
    if @service.save
      redirect_to "/profiles/#{current_user.id}"
    else
      render :new
    end
  end
  
  def destroy
    @service = Service.find(params[:id])
    @service.destroy
  end
  
  def edit
    @service = Service.find(params[:id])
    params[:seeking_help] ||= @service.seeking_help.to_s
  end

  def update
    @service = Service.find(params[:id])
    @service.update_attributes(params[:service].permit([:headline, :description, :fixed_rate, :price, :category_id, :seeking_help, :expiration_date]))

    if @service.update_attributes(params[:service].permit([:headline, :description, :fixed_rate, :price, :category_id]))
      redirect_to "/profiles/#{current_user.id}"
    else
      render :edit
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/index.html.erb
<section class = "banner">
    <div class = "container text-center">

		<form id="catalog-filter">

			<div class = "module per33">
        Within this many miles: <input name="within" type = "number" value="<%= params[:within] %>">
			</div>

			<!-- div class = "module per33">
				<input type = "checkbox" value = "for hire">For hire
				<input type = "checkbox" value = "offers">Seeking work
			</div -->

			<div class = "module per33">
				<input type="submit"/>
			</div>

		</form>

        <div class = "module-container">
        <h3 class = "large margin-bottom">Postings</h3>

				<%- @services.all.each do |service| -%>

				<div class = "module per25 tab-per50 servicesOfferedListingModule padding-medium">
					<%= link_to show_service_path(service) do %>
					<div class = "module-container servicesOfferedListingContainer" >

						<div class = "module moduleServiceOfferedTitle per100 text-center bold padding-small">
							<%= service.headline %>
						</div>
						<div class = "module moduleServiceOfferedCat per100 text-center bold">
							<%= service.category.try(:category_name) %>
						</div>
						<div class = "module moduleServiceOfferedPhoto per100 text-center ">
              <img src = "<%= service.user.avatar.url(:thumb) %>" class = "service-profile-picture">
						</div>
						<div class = "module moduleServiceOfferedName per100 text-center padding-small">
							<%= service.user.name %>
						</div>
						<div class = "module moduleServiceOfferedPrice per100 text-center padding-bottom-small">
							<%= number_to_currency(service.price) %>/<%= service.fixed_rate ? 'job' : 'hr' %>
						</div>
					</div>
					<%- end -%>
				</div>
				<%- end -%>
            </div>
		</div>
</section>

app/views/catalog/show.html.erb
<section class = "banner">
    <div class = "container align-center">
		<div class = "module per100 margin-bottom">
            <h2><%= @service.headline  %></h2>
            <h3 class = "margin-bottom">by <%= link_to @service.user.name, profile_path(@service.user.id) %><br><%= number_to_currency(@service.price) %>/<%= @service.fixed_rate ? 'job' : 'hour' %></h3>
            <p><%= @service.description %></p>
        </div>
		<%-  if current_user != @service.user-%>
		<div class = "module per100 ">
            <%= link_to "Hire", new_service_order_path(@service), :class => 'button per30 tab-per50 mob-per80 margin-bottom text-center primary-color' %>
        </div>
		<%-end -%>

	</div>
</section>

app/views/catelog/index.html.erb
<h3>Gig Catelog</h3>

<table>
	<tr>
		<th>Gig Headline</th>
		<th>Gig Provider</th>
		<th>Gig Price</th>
	</tr>
	<%- Service.all.each do |service| -%>
		<tr>
		<td><%= link_to service.headline, show_service_path(service) %></td>
		<td><%= service.user.name %></td>
		<td><%= number_to_currency(service.price) %></td>
	</tr>
	<%- end -%>
</table>

app/views/dashboard/index.html.erb
<section class = "banner" id = "banner-dashboard">
    <div class = "container">
        <!-- <div class = "module per20 padding-top-large padding-bottom-large" id = "module-dashboard-actions">
            <div class = "module-container">
                <div class = "module per100 padding-medium text-center margin-bottom margin-top">
                    <img class = "image-profile-picture" src = "img/goat picture.jpg">
                    <p class = "margin-top bold large"><%= current_user.name %></p>
                    <p class = "margin-top"><%= current_user.about_me %></p>
                </div>

                <%= link_to "View Profile", profile_path(current_user.id), :class => 'button per100 module-dashboard-action text-left' %>

                <%= link_to "Edit Profile", edit_user_registration_path, :class => 'button per100 module-dashboard-action text-left' %>

                <%= link_to "Create Service", new_service_path, :class => 'button per100 module-dashboard-action text-left'  %>

                <div class = "module per100 padding-small module-dashboard-action">
                    <p>Post Gig For Hire</p>
                </div>

                <%= link_to "Search Gigs", catalog_path, :class => 'button per100 module-dashboard-action text-left'  %>
            </div>
        </div> -->
        <!-- <div class = "module per100">
            <div class = "module-container"> -->
                <div class = "module per33 tab-per100 padding-right-medium">
                    <h3 class = "margin-bottom">Upcoming gigs and hires</h3>

                    <%- current_user.accepted_orders_i_have_or_placed.each do |order| -%>
                    <%- if !order.complete? -%>
                        <div class = "panel-notification <%= order.service.seeking_help? ? "hire" : "gig" %>">
                            <%- if order.service.seeking_help? -%>
                                <p class = "panel-title bold"><%= link_to order.user.name, profile_path(order.user.id) %> is working for you!</p>
                            <%- else -%>
                                <p class = "panel-title bold"><%= link_to order.user.name, profile_path(order.user.id) %> hired you!</p>
                            <%- end -%>

                          <p class = "panel-title bold margin-top"><%= link_to order.headline.titleize, show_service_path(order.service) %></p>
                          <p class = "panel-cost bold"><%= number_to_currency(order.price) %>/<%= order.service.fixed_rate ? 'job' : 'hour' %></p>
                          <p class = "panel-contact"><%= order.appointment_time.strftime("%_-m/%d/%Y %l:%M%P") %></p>
                      </div>
                      <div class = "module-make-connection padding-mini text-center margin-bottom module per100">
                            <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, cancel_service_order_path(order.service, order), method: :post, :class => 'padding-right-small', data: { confirm: "Are you sure you want to do that?" } %>
                            <%= link_to '<i class="fa fa-check" aria-hidden="true"></i>'.html_safe, complete_service_order_path(order.service, order), method: :post, :class => 'padding-left-small'%>
                       </div>

                    <%- end -%>

                    <%- end -%>
                </div>

                <div class = "module per33 tab-per100 padding-left-small padding-right-small">
                    <h3 class = "margin-bottom">Pending Incoming offers</h3>

                   <%- current_user.orders.unaccepted_awaiting_response.each do |order| -%>
                      <div class = "panel-notification  <%= order.service.seeking_help ? 'hire' : 'gig' =%>">
                          <%- if order.service.seeking_help? -%>
                              <p class = "panel-title bold"><%= link_to order.user.name, profile_path(order.user.id) %> wants to work for you!</p>
                          <%- else -%>
                              <p class = "panel-title bold"><%= link_to order.user.name, profile_path(order.user.id) %> wants to hire you!</p>
                          <%- end -%>
                          <p class = "panel-title bold margin-top"><%= link_to order.headline.titleize, show_service_path(order.service) %></p>
                          <p class = "panel-cost bold"><%= number_to_currency(order.price) %>/<%= order.service.fixed_rate ? 'job' : 'hour' %></p>
                          <p class = "panel-contact"><%= order.appointment_time.strftime("%_-m/%d/%Y %l:%M%P") %></p>
                      </div>

                      <div class = "module-make-connection padding-mini text-center margin-bottom module per100">
                            <%= link_to 'Accept'.html_safe, accept_service_order_path(order.service, order), method: :post, :class => 'padding-right-small' %>
                            <%= link_to 'Reject'.html_safe, reject_service_order_path(order.service, order), method: :post, :class => 'padding-left-small'%>
                       </div>
                    <%- end -%>
                </div>

                <div class = "module per33 tab-per100 padding-left-medium">
                    <h3 class = "margin-bottom">Pending Outgoing offers</h3>

                    <%- current_user.orders_i_placed.unaccepted.each do |order| -%>
                      <div class = "panel-notification <%= order.service.seeking_help ? 'gig' : 'hire' =%>">
                          <%- if order.service.seeking_help? -%>
                              <p class = "panel-title bold">You want to work for <%= link_to order.service.user.name, profile_path(order.service.user.id) %>!</p>
                          <%- else -%>
                              <p class = "panel-title bold">You want to hire <%= link_to order.service.user.name, profile_path(order.service.user.id) %>!</p>
                          <%- end -%>
                          <p class = "panel-title bold margin-top"><%= link_to order.headline.titleize, show_service_path(order.service) %></p>
                          <p class = "panel-cost bold"><%= number_to_currency(order.price) %>/<%= order.service.fixed_rate ? 'job' : 'hour' %></p>
                          <p class = "panel-contact"><%= order.appointment_time.strftime("%_-m/%d/%Y %l:%M%P") %> </p>
                      </div>

                      <div class = "module-make-connection padding-mini text-center margin-bottom module per100">
                            <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, cancel_service_order_path(order.service, order), method: :post,  data: { confirm: "Are you sure you want to do that?" } %>

                       </div>

                    <%- end -%>
                </div>
            </div>
        <!-- </div>
    </div> -->
</section>

app/views/home/index.erb
<section class = "banner" id = "banner-welcome">
    <div class = "container align-center">
        <div class = "module per70 text-center typewriter">
            <h2 class = "text1 margin-bottom">I need to hire someone fast.</h2>
            <h2 class = "text2 margin-bottom">Super broke. Need a gig today.</h2>
        </div>

        <div class = "module per70 text-center" style = "margin-top: -30px">
            <p>Check Out Recently Posted Gigs</p>
            <%= link_to 'Search Gigs', catalog_path, :class=>'button accent-color per40 tab-per30 mob-per100 margin-top' %>
        </div>
    </div>
</section>

<section class = "banner" id = "banner-home">
    <div class = "container align-center">
        <div class = "module per70 text-center">

        </div>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
    <!-- META DATA -->
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= favicon_link_tag 'favicon.ico' %>


    <!-- SCRIPTS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- FONTS -->
    <script src="https://use.fontawesome.com/ba4ae401ed.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Dosis:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">

    <!-- STYLES -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    </head>

    <body>
        <header class = "banner">
            <div class = "container align-middle">
                <div class = "module per30 mob-per80 inverse" id = "logo">
                    <h1><%= link_to image_tag("gitchMeLogo.png", :alt => "gitch logo"), root_path, :class=>'logo' %></h1>
                </div>

                <div class = "module per70 mob-per20 text-right inverse">
                    <%- if current_user -%>
                        <div class = "hamburger margin-right"><i class = "fa fa-bars" aria-hidden = "true"></i></div>
                    <%- else -%>
                        <%= link_to "Sign Up", new_user_registration_path %> |
                        <%= link_to "Login", new_user_session_path %>
                    <%- end -%>
                </div>
            </div>
        </header>

        <%- if current_user -%>
        <section class = "banner" id = "banner-sidebar">
            <div class = "container-extender">
                <div class = "module per100">
                    <div class = "module close per100 padding-medium">
                        <i class = "fa fa-close" aria-hidden = "true"></i>
                    </div>

                    <div class = "module per100 padding-medium text-center margin-bottom margin-top">
                        <img class = "image-profile-picture" src = "<%= current_user.avatar.url(:thumb) %>" style = "width: 100px">
                        <p class = "margin-top bold large"><%= current_user.name %></p>
                        <p class = "margin-top"><%= current_user.about_me %></p>
                    </div>

                    <%= link_to "Dashboard", dashboard_path, :class => 'button per100 module-dashboard-action text-center' %>

                    <%= link_to "View Profile", profile_path(current_user.id), :class => 'button per100 module-dashboard-action text-center' %>

                    <%= link_to "Edit Profile", edit_user_registration_path, :class => 'button per100 module-dashboard-action text-center' %>

                    <%= link_to "Create Service", new_service_path(:seeking_help=>'false'), :class => 'button per100 module-dashboard-action text-center'  %>

                    <%= link_to "Post Gig For Hire", new_service_path(:seeking_help=>'true'), :class => 'button per100 module-dashboard-action text-center'  %>

                    <%= link_to "Search Gigs", catalog_path, :class => 'button per100 module-dashboard-action text-center'  %>

                    <%= link_to "Logout", destroy_user_session_path,  :method => :delete, :class => 'button per100 module-dashboard-action text-center'  %>
                </div>
            </div>
        </section>
        <%- end -%>

        <%= yield %>

        <%- if request.path != '/dashboard' -%>
        <footer class = "banner" id = "banner-footer">
            <div class = "container align-center">
                <!-- <div class = "module per33 padding-medium">
                    <p>Report</p>
                    <p>Dispute an interaction</p>
                    <p>Terms and Conditions</p>
                    <p>Privacy Policy</p>
                </div> -->

                <div class = "module per50 padding-medium">
                  <p><%= link_to "Search Gigs", catalog_path %></p>
                  <%- if current_user -%><p><%= link_to "View Dashboard", dashboard_path %></p><%- end -%>
                </div>

                <div class = "module per50 padding-medium">
                  <!--<p>Social Media Icons</p>-->
                    <p><%= link_to "Contact Us", "mailto:contact@gitch.me", :class=>'button primary-color per50 text-center' %></p>
                </div>

                <div class = "module per100 padding-medium">
                    <p class = "padding-top-large small">&copy; TechTalk Laramie 2017.</p>
                </div>
            </div>
        </footer>
        <%- end -%>
    </body>
</html>

app/views/orders/new.html.erb
<section class = "banner">
    <div class = "container">
		<div class = "module per100 padding-bottom-large">
			<!--Add a link back to the service link on the headline-->
			<h3>Create an appointment for: <%= link_to @service.headline, show_service_path(@service) %></h3>
		</div>
		
			<%= form_for(@order, url: service_orders_path(@service)) do |f| -%>
			<div class = "module per100 text-left padding-bottom-small">
			   Choose an <%= f.label :appointment_time %>
			</div>
			
				<div class = "module per100 text-left">
					<div class = "module per100">Date:</div>
					<div class = "module per100">
						<input type="date" id="createApointmentDate" class = "createAppointmentDateTime">
					</div>
				</div>
			
				<div class = "module per100ext-left padding-top-medium">
					<div class = "module per100">
						Time:
					</div>
						<div class = "module per100">
							<input type="time" id="createApointmentTime"  class = "createAppointmentDateTime" step="60">
						</div>
				</div>

			<div class = "module per100 text-center hidden">
			    <%= f.datetime_field :appointment_time, :id=>"formDateTimeFieldNewAppointment" %>
			</div>
			<div class = "module per100 text-center padding-top-large">
			  <%= submit_tag "Place Order", :class=>"button per50 text-center"%>
		  </div>
		  <%- end -%>
	</div>
</section>

app/views/profiles/show.html.erb
<section class = "banner" id = "banner-profile">
    <div class = "container">
        <div class = "module per100 margin-bottom padding-bottom-large">
            <h2 class = "margin-bottom"><%= link_to @user.name || @user.email, profile_path(@user.id) %></h2>
            <div class = "module-container">
                <div class = "module per10">
                  <img class = "image-profile-picture" src = "<%= @user.avatar.url(:thumb) %>">
                </div>

                <div class = "module per90 padding-left-medium">
                    <p><%= @user.about_me %></p>
                </div>
            </div>
        </div>

        <div class = "module padding-right-medium per50">
            <h3 class = "margin-bottom">Recent Posts</h3>

            <div class = "module-container">
                <%= render partial: 'services/service_list', object: @user.services %>
            </div>
        </div>

        <div class = "module padding-left-medium per50">
            <h3 class = "margin-bottom">Reviews</h3>
            <%- @user.reviews.each do |review| -%>

            <div class = "module per100 margin-bottom">
                <%- $i = 1 -%>
                <%- $rating = review.rating.to_i + 1 -%>
                <%- until $i >= $rating do -%>
                  <i class="fa fa-star" aria-hidden="true"></i>
                  <%- $i+=1 -%>
                <%- end -%>

               <p>On <%= Date.parse(review.created_at.to_s).strftime("%m/%d/%Y") %>, <%= link_to review.from_user.name, profile_path(review.from_user.id) %> said <%= review.description %></p>
              <!-- <p>
                For <%= review.order.service.headline %> at <%= review.order.appointment_time %>
              </p> -->
            </div>
            <%- end -%>
        </div>
    </div>
</section>

app/views/reviews/new.html.erb
<section class = "banner" >
    <div class = "container">
        <div class = "module per100">
            <h2 class = "margin-bottom">Leave Review for <%= @review.user.name %></h2>
            <h3><%= @service.headline.titleize  %></h3>
            
            <%= form_for(@review, url: service_order_reviews_path) do |f| %>
            
            <div class = "module-container">
                <div class = "module per100 module-review-stars margin-top margin-bottom">
                   <i class="review-star review-star-notset fa fa-star-o" aria-hidden="true"id = "star-1"></i>
                    <i class="review-star review-star-notset fa fa-star-o" aria-hidden="true"id = "star-2"></i>
                    <i class="review-star review-star-notset fa fa-star-o" aria-hidden="true"id = "star-3"></i>
                    <i class="review-star review-star-notset fa fa-star-o" aria-hidden="true"id = "star-4"></i>
                    <i class="review-star review-star-notset fa fa-star-o" aria-hidden="true"id = "star-5"></i>
                </div>
                
                <div class = "module per100 margin-bottom module-input">
                    <span class = "floating-label">Write Review</span>
                    <%= f.text_area :description, :class=> 'per100 medium input-floating-label' %>
                </div>
            </div>
            
            <%= f.hidden_field :rating %>
            
            <%= submit_tag "Submit Review", :class => 'button per100' %>
            <%- end -%>
        </div>
    </div>
</section>

app/views/services/_service_list.html.erb
<%- show_service_provider ||= false -%>
<%- service_list.each do |service| -%>

    <div class = "panel-notification <%= service.seeking_help ? 'gig' : 'hire' =%> service_<%= service.id %>">
        <p class = "panel-title bold"><%= link_to service.headline, show_service_path(service) %></p>
        <span class = "panel-cost bold"><%= number_to_currency(service.price) %>/<%= service.fixed_rate ? 'job' : 'hour' %></span>
        <p class = "panel-contact">Posted at <%= service.created_at.strftime("%m/%d/%Y %l:%M%P") %></p>
    </div>

    <%- if current_user.id != @user.id -%>
        <%= link_to "Hire", new_service_order_path(service), :class =>'module-make-connection padding-mini text-center margin-bottom module per100' %>
    <%- else -%>
    <div class = "module-make-connection padding-mini text-center margin-bottom module per100 service_<%= service.id %>">
        <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, service_path(service), :class => 'padding-right-small', data: { confirm: "Are you sure you want to do that?" }, method: :delete, remote: true %>
        <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_service_path(service), :class => 'padding-left-small'%>
    </div>
    <%- end -%>

<%- end -%>

app/views/services/destroy.js.erb
$(function() {
  var elements = $('.service_<%= @service.id %>');
  elements.remove();
})

app/views/services/edit.html.erb
<%=
    extra_params = { :seeking_help => @service.seeking_help }
    render 'form', service: @service, extra_params: extra_params
%>

app/views/services/new.html.erb
<%=
    extra_params = {:seeking_help => params[:seeking_help]}
    render 'form', service: @service, extra_params: extra_params
%>